sylius_resource:
    resources:
        lemisoft_sylius_invoice_request_plugin.gus_configuration:
            driver: doctrine/orm
            classes:
                model: Lemisoft\SyliusInvoiceRequestPlugin\Entity\GusConfiguration
